<template>
  <div class="about">
    <el-card class="box-card">
      <el-tabs v-model="activeName" class="demo-tabs" @tab-click="handleClick">
        <el-tab-pane label="社保报表" name="first"></el-tab-pane>
      </el-tabs>
      <el-table :data="tableData" style="width: 100%" border>
        <el-table-column type="index" label="序号" width="180px" />
        <el-table-column prop="username" label="姓名" width="180px" />
        <el-table-column prop="timeOfEntry" label="入职时间" width="180px" />
        <el-table-column prop="mobile" label="手机号" width="180px" />
        <el-table-column prop="idNumber" label="身份证号码" width="180px" />
        <el-table-column
          prop="theHighestDegreeOfEducation"
          label="学历"
          width="180px"
        />
        <el-table-column prop="address" label="开户行" width="180px" />
        <el-table-column
          prop="firstLevelDepartment"
          label="一级部门"
          width="180px"
        />
        <el-table-column prop="address" label="二级部门" width="180px" />
        <el-table-column prop="address" label="工作城市" width="180px" />
        <el-table-column
          prop="socialSecurityComputerNumber"
          label="社保电脑号"
          width="180px"
        />
        <el-table-column prop="address" label="公积金账号" width="180px" />
        <el-table-column prop="address" label="离职时间" width="180px" />
        <el-table-column prop="address" label="户籍类型" width="180px" />
        <el-table-column
          prop="participatingInTheCity"
          label="参保城市"
          width="180px"
        />
        <el-table-column
          prop="socialSecurityMonth"
          label="社保月份"
          width="180px"
        />
        <el-table-column
          prop="socialSecurityBase"
          label="社保基数"
          width="180px"
        />
        <el-table-column prop="socialSecurity" label="社保合计" width="180px" />
        <el-table-column
          prop="socialSecurityEnterprise"
          label="社保企业"
          width="180px"
        />
        <el-table-column
          prop="socialSecurityIndividual"
          label="社保个人"
          width="180px"
        />
        <el-table-column
          prop="providentFundCity"
          label="公积金城市"
          width="180px"
        />
        <el-table-column
          prop="providentFundMonth"
          label="公积金月份"
          width="180px"
        />
        <el-table-column
          prop="providentFundBase"
          label="公积金基数"
          width="180px"
        />
        <el-table-column
          prop="accumulationFundEnterpriseBase"
          label="公积金企业基数"
          width="180px"
        />
        <el-table-column
          prop="personalRatioOfProvidentFund"
          label="公积金企业比例"
          width="180px"
        />
        <el-table-column
          prop="individualBaseOfProvidentFund"
          label="公积金个人基数"
          width="180px"
        />
        <el-table-column
          prop="individualBaseOfProvidentFund"
          label="公积金个人比例"
          width="180px"
        />
        <el-table-column
          prop="totalProvidentFund"
          label="公积金合计"
          width="180px"
        />
        <el-table-column
          prop="providentFundEnterprises"
          label="公积金企业"
          width="180px"
        />
        <el-table-column
          prop="providentFundIndividual"
          label="公积金个人"
          width="180px"
        />
        <el-table-column prop="address" label="养老企业基数" width="180px" />
        <el-table-column prop="address" label="养老企业比例" width="180px" />
        <el-table-column prop="address" label="养老企业" width="180px" />
        <el-table-column prop="address" label="养老个人基数" width="180px" />
        <el-table-column prop="address" label="养老个人比例" width="180px" />
        <el-table-column prop="address" label="养老个人" width="180px" />
        <el-table-column prop="address" label="失业企业基数" width="180px" />
        <el-table-column prop="address" label="失业企业比例" width="180px" />
        <el-table-column prop="address" label="失业企业" width="180px" />
        <el-table-column prop="address" label="失业个人基数" width="180px" />
        <el-table-column prop="address" label="失业企业比例" width="180px" />
        <el-table-column prop="address" label="失业个人" width="180px" />
        <el-table-column prop="address" label="医疗企业基数" width="180px" />
        <el-table-column prop="address" label="医疗企业比例" width="180px" />
        <el-table-column prop="address" label="医疗企业" width="180px" />
        <el-table-column prop="address" label="医疗个人基数" width="180px" />
        <el-table-column prop="address" label="医疗个人比例" width="180px" />
        <el-table-column prop="address" label="医疗个人" width="180px" />
        <el-table-column prop="address" label="工伤个人基数" width="180px" />
        <el-table-column prop="address" label="工伤企业比例" width="180px" />
        <el-table-column prop="address" label="工伤企业" width="180px" />
        <el-table-column prop="address" label="生育企业基数" width="180px" />
        <el-table-column prop="address" label="生育企业比例" width="180px" />
        <el-table-column prop="address" label="生育企业" width="180px" />
        <el-table-column prop="address" label="大病企业基数" width="180px" />
        <el-table-column prop="address" label="大病企业比例" width="180px" />
        <el-table-column prop="address" label="大病企业" width="180px" />
        <el-table-column prop="address" label="大病个人基数" width="180px" />
        <el-table-column prop="address" label="大病个人比例" width="180px" />
        <el-table-column prop="address" label="大病个人" width="180px" />
        <el-table-column
          prop="providentFundNotes"
          label="公积金备注"
          width="180px"
        />
        <el-table-column
          prop="socialSecurityNotes"
          label="社保备注"
          width="180px"
        />
      </el-table>

      <div class="footer">
        <el-button type="primary">归档01月份报表</el-button>
        <el-button type="primary">新建报表</el-button>
        <el-button type="info">取消</el-button>
      </div>
    </el-card>
  </div>
</template>

<script lang="ts" setup>
import { ref, reactive, toRefs } from "vue"
import { useStore } from "vuex"
import type { TabsPaneContext } from "element-plus"
import { useRouter, useRoute } from "vue-router"
const store = useStore()
const router = useRouter()
const route = useRoute()
const activeName = ref("first")
const handleClick = (tab: TabsPaneContext, event: Event) => {
  console.log(tab, event)
}
const tableData = [

      {
        id: null,
        archiveId: null,
        userId: "1063705989926227968",
        username: "管理员",
        timeOfEntry: "2018-11-02T08:00:00.000+0000",
        mobile: "13800000002",
        idNumber: null,
        theHighestDegreeOfEducation: null,
        openingBank: null,
        bankCardNumber: null,
        firstLevelDepartment: "总裁办",
        twoLevelDepartment: null,
        workingCity: null,
        socialSecurityComputerNumber: null,
        providentFundAccount: null,
        leaveDate: null,
        householdRegistrationType: null,
        participatingInTheCity: "北京",
        socialSecurityMonth: "202001",
        socialSecurityBase: 10000,
        socialSecurity: 4380.0,
        socialSecurityEnterprise: 3060.0,
        socialSecurityIndividual: 1320.0,
        providentFundCity: "北京",
        providentFundMonth: "202001",
        providentFundBase: 10000,
        accumulationFundEnterpriseBase: 10000,
        proportionOfProvidentFundEnterprises: 0.12,
        individualBaseOfProvidentFund: 10000,
        personalRatioOfProvidentFund: 0.12,
        totalProvidentFund: 24.0,
        providentFundEnterprises: 12.0,
        providentFundIndividual: 12.0,
        pensionEnterpriseBase: null,
        proportionOfPensionEnterprises: null,
        pensionEnterprise: null,
        personalPensionBase: null,
        personalPensionRatio: null,
        oldAgeIndividual: null,
        unemploymentEnterpriseBase: null,
        proportionOfUnemployedEnterprises: null,
        unemployedEnterprise: null,
        theNumberOfUnemployedIndividuals: null,
        percentageOfUnemployedIndividuals: null,
        unemployedIndividual: null,
        medicalEnterpriseBase: null,
        proportionOfMedicalEnterprises: null,
        medicalEnterprise: null,
        medicalPersonalBase: null,
        medicalPersonalRatio: null,
        medicalIndividual: null,
        baseOfIndustrialInjuryEnterprises: null,
        proportionOfIndustrialInjuryEnterprises: null,
        industrialInjuryEnterprise: null,
        fertilityEnterpriseBase: null,
        proportionOfFertilityEnterprises: null,
        childbearingEnterprise: null,
        baseOfSeriousIllness: null,
        proportionOfSeriouslyIllEnterprises: null,
        bigDiseaseEnterprise: null,
        personalBaseOfSeriousIllness: null,
        personalProportionOfSeriousIllness: null,
        providentFundNotes: "xxx12345",
        socialSecurityNotes: "xxxx",
        yearsMonth: null,
        apersonOfGreatDisease: null
      },
      {
        id: null,
        archiveId: null,
        userId: "1066370498633486336",
        username: "孙财",
        timeOfEntry: "2018-11-04T08:00:00.000+0000",
        mobile: "13800000003",
        idNumber: "1234567890",
        theHighestDegreeOfEducation: "高中",
        openingBank: null,
        bankCardNumber: null,
        firstLevelDepartment: "市场部",
        twoLevelDepartment: null,
        workingCity: null,
        socialSecurityComputerNumber: "x1111",
        providentFundAccount: null,
        leaveDate: null,
        householdRegistrationType: null,
        participatingInTheCity: "北京",
        socialSecurityMonth: "202001",
        socialSecurityBase: 3388,
        socialSecurity: 1450.064,
        socialSecurityEnterprise: 1002.848,
        socialSecurityIndividual: 447.216,
        providentFundCity: "北京",
        providentFundMonth: "202001",
        providentFundBase: 2277,
        accumulationFundEnterpriseBase: 2277,
        proportionOfProvidentFundEnterprises: 6.0,
        individualBaseOfProvidentFund: 2277,
        personalRatioOfProvidentFund: 6.0,
        totalProvidentFund: 273.24,
        providentFundEnterprises: 136.62,
        providentFundIndividual: 136.62,
        pensionEnterpriseBase: null,
        proportionOfPensionEnterprises: null,
        pensionEnterprise: null,
        personalPensionBase: null,
        personalPensionRatio: null,
        oldAgeIndividual: null,
        unemploymentEnterpriseBase: null,
        proportionOfUnemployedEnterprises: null,
        unemployedEnterprise: null,
        theNumberOfUnemployedIndividuals: null,
        percentageOfUnemployedIndividuals: null,
        unemployedIndividual: null,
        medicalEnterpriseBase: null,
        proportionOfMedicalEnterprises: null,
        medicalEnterprise: null,
        medicalPersonalBase: null,
        medicalPersonalRatio: null,
        medicalIndividual: null,
        baseOfIndustrialInjuryEnterprises: null,
        proportionOfIndustrialInjuryEnterprises: null,
        industrialInjuryEnterprise: null,
        fertilityEnterpriseBase: null,
        proportionOfFertilityEnterprises: null,
        childbearingEnterprise: null,
        baseOfSeriousIllness: null,
        proportionOfSeriouslyIllEnterprises: null,
        bigDiseaseEnterprise: null,
        personalBaseOfSeriousIllness: null,
        personalProportionOfSeriousIllness: null,
        providentFundNotes: null,
        socialSecurityNotes: "sdauy",
        yearsMonth: null,
        apersonOfGreatDisease: null
      },
      {
        id: null,
        archiveId: null,
        userId: "1071632760222810112",
        username: "罗晓晓",
        timeOfEntry: "2018-12-02T08:00:00.000+0000",
        mobile: "13800000004",
        idNumber: null,
        theHighestDegreeOfEducation: null,
        openingBank: null,
        bankCardNumber: null,
        firstLevelDepartment: "人事部",
        twoLevelDepartment: null,
        workingCity: null,
        socialSecurityComputerNumber: null,
        providentFundAccount: null,
        leaveDate: null,
        householdRegistrationType: null,
        participatingInTheCity: "北京",
        socialSecurityMonth: "202001",
        socialSecurityBase: 5000,
        socialSecurity: 2140.0,
        socialSecurityEnterprise: 1480.0,
        socialSecurityIndividual: 660.0,
        providentFundCity: "北京",
        providentFundMonth: "202001",
        providentFundBase: 5000,
        accumulationFundEnterpriseBase: 5000,
        proportionOfProvidentFundEnterprises: 12.0,
        individualBaseOfProvidentFund: 5000,
        personalRatioOfProvidentFund: 12.0,
        totalProvidentFund: 1200.0,
        providentFundEnterprises: 600.0,
        providentFundIndividual: 600.0,
        pensionEnterpriseBase: null,
        proportionOfPensionEnterprises: null,
        pensionEnterprise: null,
        personalPensionBase: null,
        personalPensionRatio: null,
        oldAgeIndividual: null,
        unemploymentEnterpriseBase: null,
        proportionOfUnemployedEnterprises: null,
        unemployedEnterprise: null,
        theNumberOfUnemployedIndividuals: null,
        percentageOfUnemployedIndividuals: null,
        unemployedIndividual: null,
        medicalEnterpriseBase: null,
        proportionOfMedicalEnterprises: null,
        medicalEnterprise: null,
        medicalPersonalBase: null,
        medicalPersonalRatio: null,
        medicalIndividual: null,
        baseOfIndustrialInjuryEnterprises: null,
        proportionOfIndustrialInjuryEnterprises: null,
        industrialInjuryEnterprise: null,
        fertilityEnterpriseBase: null,
        proportionOfFertilityEnterprises: null,
        childbearingEnterprise: null,
        baseOfSeriousIllness: null,
        proportionOfSeriouslyIllEnterprises: null,
        bigDiseaseEnterprise: null,
        personalBaseOfSeriousIllness: null,
        personalProportionOfSeriousIllness: null,
        providentFundNotes: null,
        socialSecurityNotes: null,
        yearsMonth: null,
        apersonOfGreatDisease: null
      },
      {
        id: null,
        archiveId: null,
        userId: "1074238801330704384",
        username: "文吉星",
        timeOfEntry: "2018-01-01T00:00:00.000+0000",
        mobile: "13400000001",
        idNumber: null,
        theHighestDegreeOfEducation: null,
        openingBank: null,
        bankCardNumber: null,
        firstLevelDepartment: "人事部",
        twoLevelDepartment: null,
        workingCity: null,
        socialSecurityComputerNumber: null,
        providentFundAccount: null,
        leaveDate: null,
        householdRegistrationType: null,
        participatingInTheCity: "北京",
        socialSecurityMonth: "202001",
        socialSecurityBase: 5900,
        socialSecurity: 2584.2,
        socialSecurityEnterprise: 1805.4,
        socialSecurityIndividual: 778.8,
        providentFundCity: "北京",
        providentFundMonth: "202001",
        providentFundBase: 5900,
        accumulationFundEnterpriseBase: 5900,
        proportionOfProvidentFundEnterprises: 12.0,
        individualBaseOfProvidentFund: 5900,
        personalRatioOfProvidentFund: 12.0,
        totalProvidentFund: 1416.0,
        providentFundEnterprises: 708.0,
        providentFundIndividual: 708.0,
        pensionEnterpriseBase: null,
        proportionOfPensionEnterprises: null,
        pensionEnterprise: null,
        personalPensionBase: null,
        personalPensionRatio: null,
        oldAgeIndividual: null,
        unemploymentEnterpriseBase: null,
        proportionOfUnemployedEnterprises: null,
        unemployedEnterprise: null,
        theNumberOfUnemployedIndividuals: null,
        percentageOfUnemployedIndividuals: null,
        unemployedIndividual: null,
        medicalEnterpriseBase: null,
        proportionOfMedicalEnterprises: null,
        medicalEnterprise: null,
        medicalPersonalBase: null,
        medicalPersonalRatio: null,
        medicalIndividual: null,
        baseOfIndustrialInjuryEnterprises: null,
        proportionOfIndustrialInjuryEnterprises: null,
        industrialInjuryEnterprise: null,
        fertilityEnterpriseBase: null,
        proportionOfFertilityEnterprises: null,
        childbearingEnterprise: null,
        baseOfSeriousIllness: null,
        proportionOfSeriouslyIllEnterprises: null,
        bigDiseaseEnterprise: null,
        personalBaseOfSeriousIllness: null,
        personalProportionOfSeriousIllness: null,
        providentFundNotes: "11111",
        socialSecurityNotes: "2222",
        yearsMonth: null,
        apersonOfGreatDisease: null
      },
      {
        id: null,
        archiveId: null,
        userId: "1074238801402007552",
        username: "巴思慧",
        timeOfEntry: "2018-01-01T00:00:00.000+0000",
        mobile: "13400000002",
        idNumber: null,
        theHighestDegreeOfEducation: "初中",
        openingBank: null,
        bankCardNumber: null,
        firstLevelDepartment: "人事部",
        twoLevelDepartment: null,
        workingCity: null,
        socialSecurityComputerNumber: null,
        providentFundAccount: null,
        leaveDate: null,
        householdRegistrationType: null,
        participatingInTheCity: null,
        socialSecurityMonth: null,
        socialSecurityBase: null,
        socialSecurity: null,
        socialSecurityEnterprise: 0,
        socialSecurityIndividual: 0,
        providentFundCity: null,
        providentFundMonth: null,
        providentFundBase: null,
        accumulationFundEnterpriseBase: null,
        proportionOfProvidentFundEnterprises: null,
        individualBaseOfProvidentFund: null,
        personalRatioOfProvidentFund: null,
        totalProvidentFund: null,
        providentFundEnterprises: 0,
        providentFundIndividual: 0,
        pensionEnterpriseBase: null,
        proportionOfPensionEnterprises: null,
        pensionEnterprise: null,
        personalPensionBase: null,
        personalPensionRatio: null,
        oldAgeIndividual: null,
        unemploymentEnterpriseBase: null,
        proportionOfUnemployedEnterprises: null,
        unemployedEnterprise: null,
        theNumberOfUnemployedIndividuals: null,
        percentageOfUnemployedIndividuals: null,
        unemployedIndividual: null,
        medicalEnterpriseBase: null,
        proportionOfMedicalEnterprises: null,
        medicalEnterprise: null,
        medicalPersonalBase: null,
        medicalPersonalRatio: null,
        medicalIndividual: null,
        baseOfIndustrialInjuryEnterprises: null,
        proportionOfIndustrialInjuryEnterprises: null,
        industrialInjuryEnterprise: null,
        fertilityEnterpriseBase: null,
        proportionOfFertilityEnterprises: null,
        childbearingEnterprise: null,
        baseOfSeriousIllness: null,
        proportionOfSeriouslyIllEnterprises: null,
        bigDiseaseEnterprise: null,
        personalBaseOfSeriousIllness: null,
        personalProportionOfSeriousIllness: null,
        providentFundNotes: null,
        socialSecurityNotes: null,
        yearsMonth: null,
        apersonOfGreatDisease: null
      },
      {
        id: null,
        archiveId: null,
        userId: "1075383133106425856",
        username: "乔海",
        timeOfEntry: "2018-01-01T00:00:00.000+0000",
        mobile: "13500000001",
        idNumber: null,
        theHighestDegreeOfEducation: null,
        openingBank: null,
        bankCardNumber: null,
        firstLevelDepartment: "总裁办",
        twoLevelDepartment: null,
        workingCity: null,
        socialSecurityComputerNumber: null,
        providentFundAccount: null,
        leaveDate: null,
        householdRegistrationType: null,
        participatingInTheCity: null,
        socialSecurityMonth: null,
        socialSecurityBase: null,
        socialSecurity: null,
        socialSecurityEnterprise: 0,
        socialSecurityIndividual: 0,
        providentFundCity: null,
        providentFundMonth: null,
        providentFundBase: null,
        accumulationFundEnterpriseBase: null,
        proportionOfProvidentFundEnterprises: null,
        individualBaseOfProvidentFund: null,
        personalRatioOfProvidentFund: null,
        totalProvidentFund: null,
        providentFundEnterprises: 0,
        providentFundIndividual: 0,
        pensionEnterpriseBase: null,
        proportionOfPensionEnterprises: null,
        pensionEnterprise: null,
        personalPensionBase: null,
        personalPensionRatio: null,
        oldAgeIndividual: null,
        unemploymentEnterpriseBase: null,
        proportionOfUnemployedEnterprises: null,
        unemployedEnterprise: null,
        theNumberOfUnemployedIndividuals: null,
        percentageOfUnemployedIndividuals: null,
        unemployedIndividual: null,
        medicalEnterpriseBase: null,
        proportionOfMedicalEnterprises: null,
        medicalEnterprise: null,
        medicalPersonalBase: null,
        medicalPersonalRatio: null,
        medicalIndividual: null,
        baseOfIndustrialInjuryEnterprises: null,
        proportionOfIndustrialInjuryEnterprises: null,
        industrialInjuryEnterprise: null,
        fertilityEnterpriseBase: null,
        proportionOfFertilityEnterprises: null,
        childbearingEnterprise: null,
        baseOfSeriousIllness: null,
        proportionOfSeriouslyIllEnterprises: null,
        bigDiseaseEnterprise: null,
        personalBaseOfSeriousIllness: null,
        personalProportionOfSeriousIllness: null,
        providentFundNotes: null,
        socialSecurityNotes: null,
        yearsMonth: null,
        apersonOfGreatDisease: null
      },
      {
        id: null,
        archiveId: null,
        userId: "1075383135371350016",
        username: "董昊空",
        timeOfEntry: "2018-01-01T00:00:00.000+0000",
        mobile: "13500000002",
        idNumber: null,
        theHighestDegreeOfEducation: null,
        openingBank: null,
        bankCardNumber: null,
        firstLevelDepartment: "总裁办",
        twoLevelDepartment: null,
        workingCity: null,
        socialSecurityComputerNumber: null,
        providentFundAccount: null,
        leaveDate: null,
        householdRegistrationType: null,
        participatingInTheCity: null,
        socialSecurityMonth: null,
        socialSecurityBase: null,
        socialSecurity: null,
        socialSecurityEnterprise: 0,
        socialSecurityIndividual: 0,
        providentFundCity: null,
        providentFundMonth: null,
        providentFundBase: null,
        accumulationFundEnterpriseBase: null,
        proportionOfProvidentFundEnterprises: null,
        individualBaseOfProvidentFund: null,
        personalRatioOfProvidentFund: null,
        totalProvidentFund: null,
        providentFundEnterprises: 0,
        providentFundIndividual: 0,
        pensionEnterpriseBase: null,
        proportionOfPensionEnterprises: null,
        pensionEnterprise: null,
        personalPensionBase: null,
        personalPensionRatio: null,
        oldAgeIndividual: null,
        unemploymentEnterpriseBase: null,
        proportionOfUnemployedEnterprises: null,
        unemployedEnterprise: null,
        theNumberOfUnemployedIndividuals: null,
        percentageOfUnemployedIndividuals: null,
        unemployedIndividual: null,
        medicalEnterpriseBase: null,
        proportionOfMedicalEnterprises: null,
        medicalEnterprise: null,
        medicalPersonalBase: null,
        medicalPersonalRatio: null,
        medicalIndividual: null,
        baseOfIndustrialInjuryEnterprises: null,
        proportionOfIndustrialInjuryEnterprises: null,
        industrialInjuryEnterprise: null,
        fertilityEnterpriseBase: null,
        proportionOfFertilityEnterprises: null,
        childbearingEnterprise: null,
        baseOfSeriousIllness: null,
        proportionOfSeriouslyIllEnterprises: null,
        bigDiseaseEnterprise: null,
        personalBaseOfSeriousIllness: null,
        personalProportionOfSeriousIllness: null,
        providentFundNotes: null,
        socialSecurityNotes: null,
        yearsMonth: null,
        apersonOfGreatDisease: null
      },
      {
        id: null,
        archiveId: null,
        userId: "1075383135459430400",
        username: "周乐天",
        timeOfEntry: "2018-01-01T00:00:00.000+0000",
        mobile: "13500000003",
        idNumber: null,
        theHighestDegreeOfEducation: null,
        openingBank: null,
        bankCardNumber: null,
        firstLevelDepartment: "财务部",
        twoLevelDepartment: null,
        workingCity: null,
        socialSecurityComputerNumber: null,
        providentFundAccount: null,
        leaveDate: null,
        householdRegistrationType: null,
        participatingInTheCity: null,
        socialSecurityMonth: null,
        socialSecurityBase: null,
        socialSecurity: null,
        socialSecurityEnterprise: 0,
        socialSecurityIndividual: 0,
        providentFundCity: null,
        providentFundMonth: null,
        providentFundBase: null,
        accumulationFundEnterpriseBase: null,
        proportionOfProvidentFundEnterprises: null,
        individualBaseOfProvidentFund: null,
        personalRatioOfProvidentFund: null,
        totalProvidentFund: null,
        providentFundEnterprises: 0,
        providentFundIndividual: 0,
        pensionEnterpriseBase: null,
        proportionOfPensionEnterprises: null,
        pensionEnterprise: null,
        personalPensionBase: null,
        personalPensionRatio: null,
        oldAgeIndividual: null,
        unemploymentEnterpriseBase: null,
        proportionOfUnemployedEnterprises: null,
        unemployedEnterprise: null,
        theNumberOfUnemployedIndividuals: null,
        percentageOfUnemployedIndividuals: null,
        unemployedIndividual: null,
        medicalEnterpriseBase: null,
        proportionOfMedicalEnterprises: null,
        medicalEnterprise: null,
        medicalPersonalBase: null,
        medicalPersonalRatio: null,
        medicalIndividual: null,
        baseOfIndustrialInjuryEnterprises: null,
        proportionOfIndustrialInjuryEnterprises: null,
        industrialInjuryEnterprise: null,
        fertilityEnterpriseBase: null,
        proportionOfFertilityEnterprises: null,
        childbearingEnterprise: null,
        baseOfSeriousIllness: null,
        proportionOfSeriouslyIllEnterprises: null,
        bigDiseaseEnterprise: null,
        personalBaseOfSeriousIllness: null,
        personalProportionOfSeriousIllness: null,
        providentFundNotes: null,
        socialSecurityNotes: null,
        yearsMonth: null,
        apersonOfGreatDisease: null
      },
      {
        id: null,
        archiveId: null,
        userId: "1235396724497268736",
        username: "吕勇锐",
        timeOfEntry: "1992-08-04T08:00:00.000+0000",
        mobile: "13600000001",
        idNumber: null,
        theHighestDegreeOfEducation: null,
        openingBank: null,
        bankCardNumber: null,
        firstLevelDepartment: "总裁办",
        twoLevelDepartment: null,
        workingCity: null,
        socialSecurityComputerNumber: null,
        providentFundAccount: null,
        leaveDate: null,
        householdRegistrationType: null,
        participatingInTheCity: null,
        socialSecurityMonth: null,
        socialSecurityBase: null,
        socialSecurity: null,
        socialSecurityEnterprise: 0,
        socialSecurityIndividual: 0,
        providentFundCity: null,
        providentFundMonth: null,
        providentFundBase: null,
        accumulationFundEnterpriseBase: null,
        proportionOfProvidentFundEnterprises: null,
        individualBaseOfProvidentFund: null,
        personalRatioOfProvidentFund: null,
        totalProvidentFund: null,
        providentFundEnterprises: 0,
        providentFundIndividual: 0,
        pensionEnterpriseBase: null,
        proportionOfPensionEnterprises: null,
        pensionEnterprise: null,
        personalPensionBase: null,
        personalPensionRatio: null,
        oldAgeIndividual: null,
        unemploymentEnterpriseBase: null,
        proportionOfUnemployedEnterprises: null,
        unemployedEnterprise: null,
        theNumberOfUnemployedIndividuals: null,
        percentageOfUnemployedIndividuals: null,
        unemployedIndividual: null,
        medicalEnterpriseBase: null,
        proportionOfMedicalEnterprises: null,
        medicalEnterprise: null,
        medicalPersonalBase: null,
        medicalPersonalRatio: null,
        medicalIndividual: null,
        baseOfIndustrialInjuryEnterprises: null,
        proportionOfIndustrialInjuryEnterprises: null,
        industrialInjuryEnterprise: null,
        fertilityEnterpriseBase: null,
        proportionOfFertilityEnterprises: null,
        childbearingEnterprise: null,
        baseOfSeriousIllness: null,
        proportionOfSeriouslyIllEnterprises: null,
        bigDiseaseEnterprise: null,
        personalBaseOfSeriousIllness: null,
        personalProportionOfSeriousIllness: null,
        providentFundNotes: null,
        socialSecurityNotes: null,
        yearsMonth: null,
        apersonOfGreatDisease: null
      },
      {
        id: null,
        archiveId: null,
        userId: "1235396819959627776",
        username: "袁永安",
        timeOfEntry: "1993-08-04T08:00:00.000+0000",
        mobile: "13600000002",
        idNumber: null,
        theHighestDegreeOfEducation: null,
        openingBank: null,
        bankCardNumber: null,
        firstLevelDepartment: "总裁办",
        twoLevelDepartment: null,
        workingCity: null,
        socialSecurityComputerNumber: null,
        providentFundAccount: null,
        leaveDate: null,
        householdRegistrationType: null,
        participatingInTheCity: null,
        socialSecurityMonth: null,
        socialSecurityBase: null,
        socialSecurity: null,
        socialSecurityEnterprise: 0,
        socialSecurityIndividual: 0,
        providentFundCity: null,
        providentFundMonth: null,
        providentFundBase: null,
        accumulationFundEnterpriseBase: null,
        proportionOfProvidentFundEnterprises: null,
        individualBaseOfProvidentFund: null,
        personalRatioOfProvidentFund: null,
        totalProvidentFund: null,
        providentFundEnterprises: 0,
        providentFundIndividual: 0,
        pensionEnterpriseBase: null,
        proportionOfPensionEnterprises: null,
        pensionEnterprise: null,
        personalPensionBase: null,
        personalPensionRatio: null,
        oldAgeIndividual: null,
        unemploymentEnterpriseBase: null,
        proportionOfUnemployedEnterprises: null,
        unemployedEnterprise: null,
        theNumberOfUnemployedIndividuals: null,
        percentageOfUnemployedIndividuals: null,
        unemployedIndividual: null,
        medicalEnterpriseBase: null,
        proportionOfMedicalEnterprises: null,
        medicalEnterprise: null,
        medicalPersonalBase: null,
        medicalPersonalRatio: null,
        medicalIndividual: null,
        baseOfIndustrialInjuryEnterprises: null,
        proportionOfIndustrialInjuryEnterprises: null,
        industrialInjuryEnterprise: null,
        fertilityEnterpriseBase: null,
        proportionOfFertilityEnterprises: null,
        childbearingEnterprise: null,
        baseOfSeriousIllness: null,
        proportionOfSeriouslyIllEnterprises: null,
        bigDiseaseEnterprise: null,
        personalBaseOfSeriousIllness: null,
        personalProportionOfSeriousIllness: null,
        providentFundNotes: null,
        socialSecurityNotes: null,
        yearsMonth: null,
        apersonOfGreatDisease: null
      },
      {
        id: null,
        archiveId: null,
        userId: "1235396891967438848",
        username: "罗英卓",
        timeOfEntry: "1993-08-04T08:00:00.000+0000",
        mobile: "13600000003",
        idNumber: null,
        theHighestDegreeOfEducation: null,
        openingBank: null,
        bankCardNumber: null,
        firstLevelDepartment: "行政部",
        twoLevelDepartment: null,
        workingCity: null,
        socialSecurityComputerNumber: null,
        providentFundAccount: null,
        leaveDate: null,
        householdRegistrationType: null,
        participatingInTheCity: null,
        socialSecurityMonth: null,
        socialSecurityBase: null,
        socialSecurity: null,
        socialSecurityEnterprise: 0,
        socialSecurityIndividual: 0,
        providentFundCity: null,
        providentFundMonth: null,
        providentFundBase: null,
        accumulationFundEnterpriseBase: null,
        proportionOfProvidentFundEnterprises: null,
        individualBaseOfProvidentFund: null,
        personalRatioOfProvidentFund: null,
        totalProvidentFund: null,
        providentFundEnterprises: 0,
        providentFundIndividual: 0,
        pensionEnterpriseBase: null,
        proportionOfPensionEnterprises: null,
        pensionEnterprise: null,
        personalPensionBase: null,
        personalPensionRatio: null,
        oldAgeIndividual: null,
        unemploymentEnterpriseBase: null,
        proportionOfUnemployedEnterprises: null,
        unemployedEnterprise: null,
        theNumberOfUnemployedIndividuals: null,
        percentageOfUnemployedIndividuals: null,
        unemployedIndividual: null,
        medicalEnterpriseBase: null,
        proportionOfMedicalEnterprises: null,
        medicalEnterprise: null,
        medicalPersonalBase: null,
        medicalPersonalRatio: null,
        medicalIndividual: null,
        baseOfIndustrialInjuryEnterprises: null,
        proportionOfIndustrialInjuryEnterprises: null,
        industrialInjuryEnterprise: null,
        fertilityEnterpriseBase: null,
        proportionOfFertilityEnterprises: null,
        childbearingEnterprise: null,
        baseOfSeriousIllness: null,
        proportionOfSeriouslyIllEnterprises: null,
        bigDiseaseEnterprise: null,
        personalBaseOfSeriousIllness: null,
        personalProportionOfSeriousIllness: null,
        providentFundNotes: null,
        socialSecurityNotes: null,
        yearsMonth: null,
        apersonOfGreatDisease: null
      },
      {
        id: null,
        archiveId: null,
        userId: "1235396953099419648",
        username: "宋高昂",
        timeOfEntry: "1993-08-04T08:00:00.000+0000",
        mobile: "13600000004",
        idNumber: null,
        theHighestDegreeOfEducation: null,
        openingBank: null,
        bankCardNumber: null,
        firstLevelDepartment: "人事部",
        twoLevelDepartment: null,
        workingCity: null,
        socialSecurityComputerNumber: null,
        providentFundAccount: null,
        leaveDate: null,
        householdRegistrationType: null,
        participatingInTheCity: null,
        socialSecurityMonth: null,
        socialSecurityBase: null,
        socialSecurity: null,
        socialSecurityEnterprise: 0,
        socialSecurityIndividual: 0,
        providentFundCity: null,
        providentFundMonth: null,
        providentFundBase: null,
        accumulationFundEnterpriseBase: null,
        proportionOfProvidentFundEnterprises: null,
        individualBaseOfProvidentFund: null,
        personalRatioOfProvidentFund: null,
        totalProvidentFund: null,
        providentFundEnterprises: 0,
        providentFundIndividual: 0,
        pensionEnterpriseBase: null,
        proportionOfPensionEnterprises: null,
        pensionEnterprise: null,
        personalPensionBase: null,
        personalPensionRatio: null,
        oldAgeIndividual: null,
        unemploymentEnterpriseBase: null,
        proportionOfUnemployedEnterprises: null,
        unemployedEnterprise: null,
        theNumberOfUnemployedIndividuals: null,
        percentageOfUnemployedIndividuals: null,
        unemployedIndividual: null,
        medicalEnterpriseBase: null,
        proportionOfMedicalEnterprises: null,
        medicalEnterprise: null,
        medicalPersonalBase: null,
        medicalPersonalRatio: null,
        medicalIndividual: null,
        baseOfIndustrialInjuryEnterprises: null,
        proportionOfIndustrialInjuryEnterprises: null,
        industrialInjuryEnterprise: null,
        fertilityEnterpriseBase: null,
        proportionOfFertilityEnterprises: null,
        childbearingEnterprise: null,
        baseOfSeriousIllness: null,
        proportionOfSeriouslyIllEnterprises: null,
        bigDiseaseEnterprise: null,
        personalBaseOfSeriousIllness: null,
        personalProportionOfSeriousIllness: null,
        providentFundNotes: null,
        socialSecurityNotes: null,
        yearsMonth: null,
        apersonOfGreatDisease: null
      },
      {
        id: null,
        archiveId: null,
        userId: "1235397035672682496",
        username: "师玉堂",
        timeOfEntry: "1993-08-04T08:00:00.000+0000",
        mobile: "13600000005",
        idNumber: null,
        theHighestDegreeOfEducation: "初中",
        openingBank: null,
        bankCardNumber: null,
        firstLevelDepartment: "财务部",
        twoLevelDepartment: null,
        workingCity: null,
        socialSecurityComputerNumber: null,
        providentFundAccount: null,
        leaveDate: null,
        householdRegistrationType: null,
        participatingInTheCity: null,
        socialSecurityMonth: null,
        socialSecurityBase: null,
        socialSecurity: null,
        socialSecurityEnterprise: 0,
        socialSecurityIndividual: 0,
        providentFundCity: null,
        providentFundMonth: null,
        providentFundBase: null,
        accumulationFundEnterpriseBase: null,
        proportionOfProvidentFundEnterprises: null,
        individualBaseOfProvidentFund: null,
        personalRatioOfProvidentFund: null,
        totalProvidentFund: null,
        providentFundEnterprises: 0,
        providentFundIndividual: 0,
        pensionEnterpriseBase: null,
        proportionOfPensionEnterprises: null,
        pensionEnterprise: null,
        personalPensionBase: null,
        personalPensionRatio: null,
        oldAgeIndividual: null,
        unemploymentEnterpriseBase: null,
        proportionOfUnemployedEnterprises: null,
        unemployedEnterprise: null,
        theNumberOfUnemployedIndividuals: null,
        percentageOfUnemployedIndividuals: null,
        unemployedIndividual: null,
        medicalEnterpriseBase: null,
        proportionOfMedicalEnterprises: null,
        medicalEnterprise: null,
        medicalPersonalBase: null,
        medicalPersonalRatio: null,
        medicalIndividual: null,
        baseOfIndustrialInjuryEnterprises: null,
        proportionOfIndustrialInjuryEnterprises: null,
        industrialInjuryEnterprise: null,
        fertilityEnterpriseBase: null,
        proportionOfFertilityEnterprises: null,
        childbearingEnterprise: null,
        baseOfSeriousIllness: null,
        proportionOfSeriouslyIllEnterprises: null,
        bigDiseaseEnterprise: null,
        personalBaseOfSeriousIllness: null,
        personalProportionOfSeriousIllness: null,
        providentFundNotes: null,
        socialSecurityNotes: null,
        yearsMonth: null,
        apersonOfGreatDisease: null
      },
      {
        id: null,
        archiveId: null,
        userId: "1235397109127528448",
        username: "武高丽",
        timeOfEntry: "1993-08-04T08:00:00.000+0000",
        mobile: "13600000006",
        idNumber: null,
        theHighestDegreeOfEducation: null,
        openingBank: null,
        bankCardNumber: null,
        firstLevelDepartment: "技术部",
        twoLevelDepartment: null,
        workingCity: null,
        socialSecurityComputerNumber: null,
        providentFundAccount: null,
        leaveDate: null,
        householdRegistrationType: null,
        participatingInTheCity: null,
        socialSecurityMonth: null,
        socialSecurityBase: null,
        socialSecurity: null,
        socialSecurityEnterprise: 0,
        socialSecurityIndividual: 0,
        providentFundCity: null,
        providentFundMonth: null,
        providentFundBase: null,
        accumulationFundEnterpriseBase: null,
        proportionOfProvidentFundEnterprises: null,
        individualBaseOfProvidentFund: null,
        personalRatioOfProvidentFund: null,
        totalProvidentFund: null,
        providentFundEnterprises: 0,
        providentFundIndividual: 0,
        pensionEnterpriseBase: null,
        proportionOfPensionEnterprises: null,
        pensionEnterprise: null,
        personalPensionBase: null,
        personalPensionRatio: null,
        oldAgeIndividual: null,
        unemploymentEnterpriseBase: null,
        proportionOfUnemployedEnterprises: null,
        unemployedEnterprise: null,
        theNumberOfUnemployedIndividuals: null,
        percentageOfUnemployedIndividuals: null,
        unemployedIndividual: null,
        medicalEnterpriseBase: null,
        proportionOfMedicalEnterprises: null,
        medicalEnterprise: null,
        medicalPersonalBase: null,
        medicalPersonalRatio: null,
        medicalIndividual: null,
        baseOfIndustrialInjuryEnterprises: null,
        proportionOfIndustrialInjuryEnterprises: null,
        industrialInjuryEnterprise: null,
        fertilityEnterpriseBase: null,
        proportionOfFertilityEnterprises: null,
        childbearingEnterprise: null,
        baseOfSeriousIllness: null,
        proportionOfSeriouslyIllEnterprises: null,
        bigDiseaseEnterprise: null,
        personalBaseOfSeriousIllness: null,
        personalProportionOfSeriousIllness: null,
        providentFundNotes: null,
        socialSecurityNotes: null,
        yearsMonth: null,
        apersonOfGreatDisease: null
      },
      {
        id: null,
        archiveId: null,
        userId: "1235397192455766016",
        username: "任志行",
        timeOfEntry: "1993-08-04T08:00:00.000+0000",
        mobile: "13600000007",
        idNumber: null,
        theHighestDegreeOfEducation: null,
        openingBank: null,
        bankCardNumber: null,
        firstLevelDepartment: "运营部",
        twoLevelDepartment: null,
        workingCity: null,
        socialSecurityComputerNumber: null,
        providentFundAccount: null,
        leaveDate: null,
        householdRegistrationType: null,
        participatingInTheCity: null,
        socialSecurityMonth: null,
        socialSecurityBase: null,
        socialSecurity: null,
        socialSecurityEnterprise: 0,
        socialSecurityIndividual: 0,
        providentFundCity: null,
        providentFundMonth: null,
        providentFundBase: null,
        accumulationFundEnterpriseBase: null,
        proportionOfProvidentFundEnterprises: null,
        individualBaseOfProvidentFund: null,
        personalRatioOfProvidentFund: null,
        totalProvidentFund: null,
        providentFundEnterprises: 0,
        providentFundIndividual: 0,
        pensionEnterpriseBase: null,
        proportionOfPensionEnterprises: null,
        pensionEnterprise: null,
        personalPensionBase: null,
        personalPensionRatio: null,
        oldAgeIndividual: null,
        unemploymentEnterpriseBase: null,
        proportionOfUnemployedEnterprises: null,
        unemployedEnterprise: null,
        theNumberOfUnemployedIndividuals: null,
        percentageOfUnemployedIndividuals: null,
        unemployedIndividual: null,
        medicalEnterpriseBase: null,
        proportionOfMedicalEnterprises: null,
        medicalEnterprise: null,
        medicalPersonalBase: null,
        medicalPersonalRatio: null,
        medicalIndividual: null,
        baseOfIndustrialInjuryEnterprises: null,
        proportionOfIndustrialInjuryEnterprises: null,
        industrialInjuryEnterprise: null,
        fertilityEnterpriseBase: null,
        proportionOfFertilityEnterprises: null,
        childbearingEnterprise: null,
        baseOfSeriousIllness: null,
        proportionOfSeriouslyIllEnterprises: null,
        bigDiseaseEnterprise: null,
        personalBaseOfSeriousIllness: null,
        personalProportionOfSeriousIllness: null,
        providentFundNotes: null,
        socialSecurityNotes: null,
        yearsMonth: null,
        apersonOfGreatDisease: null
      },
      {
        id: null,
        archiveId: null,
        userId: "1235397256737669120",
        username: "瞿光明",
        timeOfEntry: "1993-08-04T08:00:00.000+0000",
        mobile: "13600000008",
        idNumber: null,
        theHighestDegreeOfEducation: null,
        openingBank: null,
        bankCardNumber: null,
        firstLevelDepartment: "市场部",
        twoLevelDepartment: null,
        workingCity: null,
        socialSecurityComputerNumber: null,
        providentFundAccount: null,
        leaveDate: null,
        householdRegistrationType: null,
        participatingInTheCity: null,
        socialSecurityMonth: null,
        socialSecurityBase: null,
        socialSecurity: null,
        socialSecurityEnterprise: 0,
        socialSecurityIndividual: 0,
        providentFundCity: null,
        providentFundMonth: null,
        providentFundBase: null,
        accumulationFundEnterpriseBase: null,
        proportionOfProvidentFundEnterprises: null,
        individualBaseOfProvidentFund: null,
        personalRatioOfProvidentFund: null,
        totalProvidentFund: null,
        providentFundEnterprises: 0,
        providentFundIndividual: 0,
        pensionEnterpriseBase: null,
        proportionOfPensionEnterprises: null,
        pensionEnterprise: null,
        personalPensionBase: null,
        personalPensionRatio: null,
        oldAgeIndividual: null,
        unemploymentEnterpriseBase: null,
        proportionOfUnemployedEnterprises: null,
        unemployedEnterprise: null,
        theNumberOfUnemployedIndividuals: null,
        percentageOfUnemployedIndividuals: null,
        unemployedIndividual: null,
        medicalEnterpriseBase: null,
        proportionOfMedicalEnterprises: null,
        medicalEnterprise: null,
        medicalPersonalBase: null,
        medicalPersonalRatio: null,
        medicalIndividual: null,
        baseOfIndustrialInjuryEnterprises: null,
        proportionOfIndustrialInjuryEnterprises: null,
        industrialInjuryEnterprise: null,
        fertilityEnterpriseBase: null,
        proportionOfFertilityEnterprises: null,
        childbearingEnterprise: null,
        baseOfSeriousIllness: null,
        proportionOfSeriouslyIllEnterprises: null,
        bigDiseaseEnterprise: null,
        personalBaseOfSeriousIllness: null,
        personalProportionOfSeriousIllness: null,
        providentFundNotes: null,
        socialSecurityNotes: null,
        yearsMonth: null,
        apersonOfGreatDisease: null
      }
]
</script>
<style lang="scss" scoped>
.footer {
  margin: 10px 0;
  text-align: center;
}
</style>